server:
  port: 8080
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: #
    username: #
    password: #

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    open-in-view: false



  redis:
    host: #
    port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: #
            client-secret: #
            scope: profile,email
  mail:
    host: smtp.naver.com
    port: 465
    username: #
    password: #
    properties:
      debug: true
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com


sens:
  serviceId: #
  accessKey: #
  secretKey: #
  senderPhone: #

jwt:
  token:
    secret: #

cloud:
  aws:
    credentials:
      accessKey:  #
      secretKey:  #
    s3:
      bucket: #
    region:
      static: ap-northeast-2
    stack:
      auto: false

kamis:
  host: https://www.kamis.or.kr/service/price/xml.do?
  key: #
  id: #

business-api:
  key:

toss:
  api:
    testSecretApiKey: #