server:
  port: 8081
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: ec2
  datasource:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true