server:
  port: 8080
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active:
  datasource:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
